# Generated by Django 5.0.7 on 2024-07-22 03:36

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blo_description',
            field=tinymce.models.HTMLField(verbose_name='Texto do Blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blo_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
