# Generated by Django 5.0.7 on 2024-07-26 18:59

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blog_blo_description_alter_blog_blo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('car_modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('car_description', tinymce.models.HTMLField(verbose_name='Texto do Blog')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='images/carro', verbose_name='Imagem de Capa')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='CategoryCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catcar_name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria do Carro')),
            ],
            options={
                'verbose_name': 'Categoria do Carro',
                'verbose_name_plural': 'Categorias de Carros',
            },
        ),
    ]
