# Generated by Django 5.0.7 on 2024-07-26 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carros_categorycar'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='car_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categorycar'),
        ),
    ]
