# Generated by Django 5.0.6 on 2024-07-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
