# Generated by Django 5.0.6 on 2024-07-17 23:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[core.validators.validate_cpf]),
        ),
    ]
