# Generated by Django 5.0.6 on 2024-07-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_category_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade em Estoque'),
        ),
    ]
