# Generated by Django 5.0.6 on 2024-07-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_products_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='description',
            new_name='blo_description',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='image',
            new_name='blo_image',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='subtitle',
            new_name='blo_subtitle',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='title',
            new_name='blo_title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='cat_name',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='cli_cpf',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='cli_email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='cli_nome',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='pro_category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='pro_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='pro_price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='stock',
            new_name='pro_stock',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cli_foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
