# Generated by Django 5.0.6 on 2024-07-18 21:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_description_blogs_blo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cli_cpf',
            field=models.CharField(max_length=11, validators=[core.validators.validate_cpf]),
        ),
    ]
